# Generated by Django 4.0.4 on 2022-06-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
