# Generated by Django 4.0.4 on 2022-06-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_game_is_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='type',
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.IntegerField(choices=[(1, 'one player'), (2, 'two players'), (3, 'one players'), (4, 'one players'), (5, 'one players')], default=1),
            preserve_default=False,
        ),
    ]
