# Generated by Django 4.0.4 on 2022-06-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_game_type_game_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.IntegerField(choices=[(1, 'one player'), (2, 'two players'), (3, 'thre players'), (4, 'four players'), (5, 'five players')]),
        ),
    ]
