# Generated by Django 4.0.4 on 2022-06-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='registrations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
